import { Injectable } from '@angular/core';
import { Order, OrderDetails, Address, User } from 'app/models/model.interface';
import { IProducts } from 'app/products';
import { HttpClient } from '@angular/common/http';

const products: IProducts[] = [
  // wash & fold for men
  { product_id: 'pd1', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd2', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd3', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd4', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},

  // wash & fold for women
  { product_id: 'pd5', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd6', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd7', product_img : 'assets/img/dress.svg', product_name : 'Gown/Dress',
  product_price : 40, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd8', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd9', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd10', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},

  // wash & fold for men contd.
  { product_id: 'pd11', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd12', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd13', product_img : '', product_name : 'Boxer',
  product_price : 12, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd14', product_img : '', product_name : 'Shorts',
  product_price : 12, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd15', product_img : '', product_name : 'Lungi/Dhoti',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd16', product_img : '', product_name : 'Sweater/Pull Over',
  product_price : 30, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd17', product_img : '', product_name : 'Sweat Shirt/ Sweat T-shirt',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd18', product_img : '', product_name : 'Winter Cap',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd19', product_img : '', product_name : 'Vest',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd20', product_img : '', product_name : 'Brief/Underwear',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd21', product_img : '', product_name : 'Track Pant/Trouser',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Men'},

  // WASH & STEAM IRON for men
  { product_id: 'pd22', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd23', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd24', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd25', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd26', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd27', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 35, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd28', product_img : '', product_name : 'Boxer',
  product_price : 15, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd29', product_img : '', product_name : 'Sweat Shirt/ Sweat T-shirt',
  product_price : 30, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Men'},

  // WASH & IRON for men
  { product_id: 'pd30', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd31', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd32', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd33', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd34', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd35', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd36', product_img : '', product_name : 'Boxer',
  product_price : 12, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd37', product_img : '', product_name : 'Shorts',
  product_price : 15, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd38', product_img : '', product_name : 'Vest',
  product_price : 12, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd39', product_img : '', product_name : 'Brief/Underwear',
  product_price : 12, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd40', product_img : '', product_name : 'Track Pant/Trouser',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Men'},

  // Express Wash for men
  { product_id: 'pd41', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd42', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd43', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd44', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd45', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 45, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd46', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd47', product_img : '', product_name : 'Boxer',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd48', product_img : '', product_name : 'Shorts',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd49', product_img : '', product_name : 'Lungi/Dhoti',
  product_price : 35, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd50', product_img : '', product_name : 'Sweater/Pull Over',
  product_price : 200, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd51', product_img : '', product_name : 'Sweat Shirt/ Sweat T-shirt',
  product_price : 80, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd52', product_img : '', product_name : 'Winter Cap',
  product_price : 50, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd53', product_img : '', product_name : 'Vest',
  product_price : 20, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd54', product_img : '', product_name : 'Brief/Underwear',
  product_price : 20, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Men'},

  // Steam iron for men
  { product_id: 'pd55', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 12, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd56', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 12, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd57', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 15, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd58', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 15, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd59', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 15, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd60', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 25, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd61', product_img : '', product_name : 'Lungi/Dhoti',
  product_price : 20, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd62', product_img : '', product_name : 'Suits(Simple)',
  product_price : 35, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd63', product_img : '', product_name : 'Sweat Shirt/ Sweat T-shirt',
  product_price : 25, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Men'},

  // Starch wash for men
  { product_id: 'pd64', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 30, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd65', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 35, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd66', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 35, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd67', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 40, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd68', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 45, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd69', product_img : '', product_name : 'Lungi/Dhoti',
  product_price : 40, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Men'},

  // Dry clean for men
  { product_id: 'pd70', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 40, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd71', product_img : 'assets/img/t-shirt.svg', product_name : 'T-Shirt',
  product_price : 35, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd72', product_img : 'assets/img/trousers.svg', product_name : 'Formal Pants',
  product_price : 35, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd73', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 40, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd74', product_img : '', product_name : 'Kurta(Simple)',
  product_price : 45, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd75', product_img : '', product_name : 'Kurta(Premium)',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd76', product_img : '', product_name : 'Boxer',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd77', product_img : '', product_name : 'Blazer(Simple)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd78', product_img : '', product_name : 'Suits(Simple)',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd79', product_img : '', product_name : 'Sweater/Pull Over',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd80', product_img : '', product_name : 'Sweat Shirt/ Sweat T-shirt',
  product_price : 50, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd81', product_img : '', product_name : 'Jacket(Half)',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd82', product_img : '', product_name : 'Jacket(Full)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd83', product_img : '', product_name : 'Winter Cap',
  product_price : 50, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd84', product_img : '', product_name : 'Blazer(Medium)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd85', product_img : '', product_name : 'Blazer(Premium)',
  product_price : 180, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd86', product_img : '', product_name : 'Suit(Medium)',
  product_price : 250, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd87', product_img : '', product_name : 'Suit(Premium)',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd88', product_img : '', product_name : 'Jacket Heavy',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd89', product_img : '', product_name : 'Sherwani(Simple)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd90', product_img : '', product_name : 'Sherwani(Premium)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd91', product_img : '', product_name : 'Waistcoat',
  product_price : 125, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd92', product_img : '', product_name : 'Tie',
  product_price : 25, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Men'},

  // Dying for men
  { product_id: 'pd93', product_img : 'assets/img/shirt.svg', product_name : 'Shirt',
  product_price : 300, product_details : 'DYING', product_quantity : 0, product_For: 'Men'},
  { product_id: 'pd94', product_img : 'assets/img/jeans.svg', product_name : 'Jeans',
  product_price : 350, product_details : 'DYING', product_quantity : 0, product_For: 'Men'},

  // wash & fold for women contd.
  { product_id: 'pd95', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd96', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 30, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd97', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd98', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd99', product_img : '', product_name : 'Saree(Premium)',
  product_price : 40, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd100', product_img : '', product_name : 'Peticoat',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd100', product_img : '', product_name : 'Sweat Shirt/Sweat T-shirt',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd101', product_img : '', product_name : 'Blouse',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd102', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd103', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd104', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 30, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd105', product_img : '', product_name : 'Night Gown',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd106', product_img : '', product_name : 'Shrug',
  product_price : 12, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd107', product_img : '', product_name : 'Bathrobe',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Women'},

  // WASH & STEAM IRON for women
  { product_id: 'pd108', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd109', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd110', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 30, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd111', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 40, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd112', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd113', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd114', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd115', product_img : '', product_name : 'Salwar Suit(2pc)',
  product_price : 40, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd116', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 45, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd117', product_img : '', product_name : 'Saree(Premium)',
  product_price : 70, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd118', product_img : '', product_name : 'Peticoat',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd119', product_img : '', product_name : 'Sweat Shirt/Sweat T-shirt',
  product_price : 25, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd120', product_img : '', product_name : 'Blouse',
  product_price : 15, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd121', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd122', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 35, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd123', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 50, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd124', product_img : 'assets/img/dress.svg', product_name : 'Gown/Dress',
  product_price : 60, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd125', product_img : '', product_name : 'Night Gown',
  product_price : 35, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Women'},

  // WASH & IRON for women
  { product_id: 'pd126', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd127', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd128', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd129', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd130', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd131', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd132', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd133', product_img : '', product_name : 'Salwar Suit(2pc)',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd134', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd135', product_img : '', product_name : 'Saree(Premium)',
  product_price : 60, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd136', product_img : '', product_name : 'Peticoat',
  product_price : 10, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd137', product_img : '', product_name : 'Sweat Shirt/Sweat T-shirt',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd138', product_img : '', product_name : 'Blouse',
  product_price : 15, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd139', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 15, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd140', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd141', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd142', product_img : 'assets/img/dress.svg', product_name : 'Gown/Dress',
  product_price : 50, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd143', product_img : '', product_name : 'Night Gown',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd144', product_img : '', product_name : 'Shrug',
  product_price : 15, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd145', product_img : '', product_name : 'Jump Suit',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Women'},

  // EXPRESS WASH for women
  { product_id: 'pd146', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd147', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd148', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 45, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd149', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 80, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd150', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd151', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 35, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd152', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd153', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 70, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd154', product_img : '', product_name : 'Peticoat',
  product_price : 25, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd155', product_img : '', product_name : 'Shawl',
  product_price : 50, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd156', product_img : '', product_name : 'Sweat Shirt/Sweat T-shirt',
  product_price : 35, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd157', product_img : '', product_name : 'Blouse',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd158', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 35, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd159', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd160', product_img : '', product_name : 'Blazer',
  product_price : 300, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd161', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 80, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd162', product_img : 'assets/img/dress.svg', product_name : 'Gown/Dress',
  product_price : 100, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd163', product_img : '', product_name : 'Night Gown',
  product_price : 70, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Women'},

  // STEAM IRON for women
  { product_id: 'pd164', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd165', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd166', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 15, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd167', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 30, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd168', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd169', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 12, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd170', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd171', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 30, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd172', product_img : '', product_name : 'Saree(Premium)',
  product_price : 40, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd173', product_img : '', product_name : 'Peticoat',
  product_price : 12, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd174', product_img : '', product_name : 'Sweat Shirt/Sweat T-shirt',
  product_price : 12, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd175', product_img : '', product_name : 'Blouse',
  product_price : 10, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd176', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 10, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd177', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 20, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd178', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 25, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd179', product_img : 'assets/img/dress.svg', product_name : 'Gown/Dress',
  product_price : 30, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd180', product_img : '', product_name : 'Night Gown',
  product_price : 20, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Women'},

  // STARCH WASH for women
  { product_id: 'pd181', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 25, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd182', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 55, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd183', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 50, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd184', product_img : '', product_name : 'Saree(Premium)',
  product_price : 90, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd185', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 25, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd186', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 60, product_details : 'STARCH WASH', product_quantity : 0, product_For: 'Women'},

  // DRY CLEAN for women
  { product_id: 'pd187', product_img : 'assets/img/blouse.svg', product_name : 'Tees/Tops',
  product_price : 40, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd188', product_img : 'assets/img/WomenShirt.svg', product_name : 'Shirt',
  product_price : 40, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd189', product_img : '', product_name : 'Kurti(Simple)',
  product_price : 45, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd190', product_img : '', product_name : 'Kurti(Premium)',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd191', product_img : 'assets/img/leggings.svg', product_name : 'Jeans/Jeggings',
  product_price : 40, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd192', product_img : '', product_name : 'Leggings/Plazzos',
  product_price : 35, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd193', product_img : '', product_name : 'Shorts/Skirt',
  product_price : 70, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd194', product_img : '', product_name : 'Salwar Suit(2pc)',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd195', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd196', product_img : '', product_name : 'Saree(Premium)',
  product_price : 110, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd197', product_img : '', product_name : 'Blouse',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd198', product_img : '', product_name : 'Dupatta(Simple)',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd199', product_img : '', product_name : 'Dupatta(Premium)',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd200', product_img : '', product_name : 'Lehenga Simple(2pc)',
  product_price : 350, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd201', product_img : '', product_name : 'Jacket/Shrugs',
  product_price : 130, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd202', product_img : '', product_name : 'Women Kurti (Fancy)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd203', product_img : '', product_name : 'Dress - Long',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd304', product_img : '', product_name : 'Anarkali Suit(Premium)',
  product_price : 400, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd205', product_img : '', product_name : 'Blouse Fancy',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd206', product_img : '', product_name : 'Skirt Long	',
  product_price : 130, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd207', product_img : '', product_name : 'Stole',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd208', product_img : '', product_name : 'Dupatta(Fancy)',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd209', product_img : '', product_name : 'Saree Embroidery',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd210', product_img : '', product_name : 'Saree Silk(Simple)',
  product_price : 70, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd211', product_img : '', product_name : 'Saree Silk(Premium)',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd212', product_img : '', product_name : 'Saree Silk(Heavy)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd213', product_img : '', product_name : 'Silk South Indian',
  product_price : 130, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd214', product_img : '', product_name : 'Saree(Patta)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd215', product_img : '', product_name : 'Lehenga Bridal(2pc)',
  product_price : 500, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd216', product_img : '', product_name : 'Lehenga Simple(3pc)',
  product_price : 400, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd217', product_img : '', product_name : 'Lehenga Bridal(3pc)',
  product_price : 600, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd218', product_img : '', product_name : 'Anarkali Suit',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd219', product_img : '', product_name : 'Salwar Suit(3PC)',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd220', product_img : '', product_name : 'Saree Bridal',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Women'},

  // MENDING SINGLE for women
  { product_id: 'pd221', product_img : '', product_name : 'Saree(Cotton)',
  product_price : 60, product_details : 'MENDING SINGLE', product_quantity : 0, product_For: 'Women'},
  { product_id: 'pd222', product_img : '', product_name : 'Saree(Patta)',
  product_price : 40, product_details : 'MENDING SINGLE', product_quantity : 0, product_For: 'Women'},

  // wash & fold for children
  { product_id: 'pd223', product_img : '', product_name : 'Shirt/T-shirt',
  product_price : 12, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd224', product_img : '', product_name : 'Pant',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd225', product_img : '', product_name : 'Socks',
  product_price : 5, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd226', product_img : '', product_name : 'Frock',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Children'},

  // WASH & STEAM IRON for children
  { product_id: 'pd227', product_img : '', product_name : 'Shirt/T-shirt',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd228', product_img : '', product_name : 'Pant',
  product_price : 20, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd229', product_img : '', product_name : 'Frock',
  product_price : 25, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Children'},

  // WASH & IRON for children
  { product_id: 'pd230', product_img : '', product_name : 'Shirt/T-shirt',
  product_price : 16, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd231', product_img : '', product_name : 'Pant',
  product_price : 15, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd232', product_img : '', product_name : 'Frock',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Children'},

  // EXPRESS WASH for children
  { product_id: 'pd233', product_img : '', product_name : 'Shirt/T-shirt',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd234', product_img : '', product_name : 'Pant',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd235', product_img : '', product_name : 'Coat/Blazer',
  product_price : 300, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd236', product_img : '', product_name : 'Socks',
  product_price : 10, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd237', product_img : '', product_name : 'Frock',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd238', product_img : '', product_name : 'Jacket',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Children'},

  // STEAM IRON for children
  { product_id: 'pd239', product_img : '', product_name : 'Shirt/T-shirt',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd240', product_img : '', product_name : 'Pant',
  product_price : 11, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd241', product_img : '', product_name : 'Frock',
  product_price : 15, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Children'},

  // DRY CLEAN for children
  { product_id: 'pd242', product_img : '', product_name : 'Pant',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd243', product_img : '', product_name : 'Coat/Blazer',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd244', product_img : '', product_name : 'Frock',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd245', product_img : '', product_name : 'Suit(Simple)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd246', product_img : '', product_name : 'Suit(Premium)',
  product_price : 180, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},
  { product_id: 'pd247', product_img : '', product_name : 'Dress',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Children'},

  // wash & fold for Household
  { product_id: 'pd248', product_img : '', product_name : 'Table Cloth(Small)',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd249', product_img : '', product_name : 'Pillow Cover',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd250', product_img : '', product_name : 'Table Cloth(Large)',
  product_price : 30, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd251', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd252', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 30, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd253', product_img : '', product_name : 'Curtains(Window)',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd254', product_img : '', product_name : 'Curtains(Door)',
  product_price : 35, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd255', product_img : '', product_name : 'Sofa Cover(Small)',
  product_price : 40, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd256', product_img : '', product_name : 'Sofa Cover(Large)',
  product_price : 60, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd257', product_img : '', product_name : 'Towel',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd258', product_img : '', product_name : 'Door Mat',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd259', product_img : '', product_name : 'Carpet(Small)',
  product_price : 100, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd260', product_img : '', product_name : 'Carpet(Medium)',
  product_price : 150, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd261', product_img : '', product_name : 'Carpet(Large)',
  product_price : 200, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd262', product_img : '', product_name : 'Blanket Cover',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd263', product_img : '', product_name : 'Small Towel',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd264', product_img : '', product_name : 'Kitchen Apron',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd265', product_img : '', product_name : 'Mosquito Curtain',
  product_price : 40, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd266', product_img : '', product_name : 'Cushion Cover',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd267', product_img : '', product_name : 'Sofaa Back Cover(Large)',
  product_price : 40, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd268', product_img : '', product_name : 'Sofaa Back Cover(Small)',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Household'},

  // WASH & STEAM IRON for Household
  { product_id: 'pd269', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 40, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd270', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 50, product_details : 'WASH & STEAM IRON', product_quantity : 0, product_For: 'Household'},

  // WASH & IRON for Household
  { product_id: 'pd271', product_img : '', product_name : 'Pillow Cover',
  product_price : 12, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd272', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd273', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd274', product_img : '', product_name : 'Curtains(Window)',
  product_price : 30, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd275', product_img : '', product_name : 'Curtains(Door)',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd276', product_img : '', product_name : 'Sofa Cover(Large)',
  product_price : 90, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd277', product_img : '', product_name : 'Towel',
  product_price : 20, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd278', product_img : '', product_name : 'Blanket Cover',
  product_price : 40, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd279', product_img : '', product_name : 'Small Towel',
  product_price : 10, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Household'},

  // EXPRESS WASH for Household
  { product_id: 'pd280', product_img : '', product_name : 'Table Cloth(Small)',
  product_price : 35, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd281', product_img : '', product_name : 'Pillow Cover',
  product_price : 20, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd282', product_img : '', product_name : 'Table Cloth(Large)',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd283', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd284', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 80, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd285', product_img : '', product_name : 'Curtains(Window)',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd286', product_img : '', product_name : 'Curtains(Door)',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd287', product_img : '', product_name : 'Sofa Cover(Small)',
  product_price : 60, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd288', product_img : '', product_name : 'Sofa Cover(Large)',
  product_price : 90, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd289', product_img : '', product_name : 'Towel',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd290', product_img : '', product_name : 'Door Mat',
  product_price : 45, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Household'},

  // STEAM IRON for Household
  { product_id: 'pd291', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 20, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd292', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 25, product_details : 'STEAM IRON', product_quantity : 0, product_For: 'Household'},

  // STARCH  WASH for Household
  { product_id: 'pd293', product_img : '', product_name : 'Table Cloth(Small)',
  product_price : 60, product_details : 'STARCH  WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd294', product_img : '', product_name : 'Pillow Cover',
  product_price : 20, product_details : 'STARCH  WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd295', product_img : '', product_name : 'Table Cloth(Large)',
  product_price : 70, product_details : 'STARCH  WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd296', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 70, product_details : 'STARCH  WASH', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd297', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 80, product_details : 'STARCH  WASH', product_quantity : 0, product_For: 'Household'},

  // DRY CLEAN for Household
  { product_id: 'pd298', product_img : '', product_name : 'Pillow Cover',
  product_price : 25, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd299', product_img : '', product_name : 'Single Bed Sheet',
  product_price : 50, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd300', product_img : '', product_name : 'Double Bed Sheet',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd301', product_img : '', product_name : 'Curtains(Door)',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd302', product_img : '', product_name : 'Blanket(Single)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd303', product_img : '', product_name : 'Blanket(Double)',
  product_price : 250, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd304', product_img : '', product_name : 'Towel',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},
  { product_id: 'pd305', product_img : '', product_name : 'Carpet(Large)',
  product_price : 450, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Household'},

  // wash & fold for Household
  { product_id: 'pd306', product_img : '', product_name : 'Handkerchief',
  product_price : 5, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd307', product_img : '', product_name : 'Socks',
  product_price : 5, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd308', product_img : '', product_name : 'Cap',
  product_price : 10, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd309', product_img : '', product_name : 'Cotton Bag',
  product_price : 15, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd310', product_img : '', product_name : 'Fridge cover',
  product_price : 20, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd311', product_img : '', product_name : 'Washing Machine/TV Cover',
  product_price : 25, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Accessories'},

  // WASH & IRON for Household
  { product_id: 'pd312', product_img : '', product_name : 'Apron',
  product_price : 25, product_details : 'WASH & IRON', product_quantity : 0, product_For: 'Accessories'},

  // EXPRESS WASH for Household
  { product_id: 'pd313', product_img : '', product_name : 'Handkerchief',
  product_price : 10, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd314', product_img : '', product_name : 'Socks',
  product_price : 10, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd315', product_img : '', product_name : 'Cap',
  product_price : 20, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd316', product_img : '', product_name : 'Cotton Bag',
  product_price : 25, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd317', product_img : '', product_name : 'Fridge cover',
  product_price : 30, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd318', product_img : '', product_name : 'Washing Machine/TV Cover',
  product_price : 40, product_details : 'EXPRESS WASH', product_quantity : 0, product_For: 'Accessories'},

  // DRY CLEAN for Household
  { product_id: 'pd319', product_img : '', product_name : 'Tie',
  product_price : 30, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd320', product_img : '', product_name : 'Apron',
  product_price : 45, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd321', product_img : '', product_name : 'Laptop Bag',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Accessories'},
  { product_id: 'pd322', product_img : '', product_name : 'Travel Bag',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Accessories'},

  // wash & fold for Winter Wear
  { product_id: 'pd323', product_img : '', product_name : 'Quilt(Single)',
  product_price : 80, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd324', product_img : '', product_name : 'Quilt(Double)',
  product_price : 130, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd325', product_img : '', product_name : 'Quilt(Medium)',
  product_price : 100, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd326', product_img : '', product_name : 'Shawl',
  product_price : 35, product_details : 'WASH & FOLD', product_quantity : 0, product_For: 'Winter Wear'},

  // DRY CLEAN for Winter Wear
  { product_id: 'pd327', product_img : '', product_name : 'Blanket(Single)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd328', product_img : '', product_name : 'Blanket(Double)',
  product_price : 250, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd329', product_img : '', product_name : 'Blanket(Medium)',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd330', product_img : '', product_name : 'Blanket(Heavy)',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd331', product_img : '', product_name : 'Quilt(Single)',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd332', product_img : '', product_name : 'Quilt(Double)',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd333', product_img : '', product_name : 'Quilt(Medium)',
  product_price : 180, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd334', product_img : '', product_name : 'Quilt(Heavy)',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd335', product_img : '', product_name : 'Muffler',
  product_price : 50, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd336', product_img : '', product_name : 'Shawl',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd337', product_img : '', product_name : 'Shawl(Heavy)',
  product_price : 150, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd338', product_img : '', product_name : 'Quilt Cover(Single)',
  product_price : 120, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd339', product_img : '', product_name : 'Quilt Cover(Double)',
  product_price : 200, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd340', product_img : '', product_name : 'Sweater(Light)',
  product_price : 60, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd341', product_img : '', product_name : 'Sweater(Medium)',
  product_price : 80, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd342', product_img : '', product_name : 'Sweater(Heavy)',
  product_price : 100, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd343', product_img : '', product_name : 'Overcoat(Medium)',
  product_price : 250, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd344', product_img : '', product_name : 'Overcoat(Long)',
  product_price : 300, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},
  { product_id: 'pd345', product_img : '', product_name : 'Leather Jacket',
  product_price : 450, product_details : 'DRY CLEAN', product_quantity : 0, product_For: 'Winter Wear'},

  // 1 PC for Addon
  { product_id: 'pd346', product_img : '', product_name : 'Packaging',
  product_price : 3, product_details : '1 PC', product_quantity : 0, product_For: 'Addon'},
  { product_id: 'pd347', product_img : '', product_name : 'Large Bag',
  product_price : 8, product_details : '1 PC', product_quantity : 0, product_For: 'Addon'},

  // WATER WASH for Vehicle Wash
  { product_id: 'pd348', product_img : '', product_name : 'Bikes/Scooters',
  product_price : 50, product_details : 'WATER WASH (Only Vehicle Wash)', product_quantity : 0, product_For: 'Vehicle Wash'},
  { product_id: 'pd349', product_img : '', product_name : 'Cars/Jeeps',
  product_price : 100, product_details : 'WATER WASH (Only Vehicle Wash)', product_quantity : 0, product_For: 'Vehicle Wash'},

  // FOAM WASH for Vehicle Wash
  { product_id: 'pd350', product_img : '', product_name : 'Bikes/Scooters',
  product_price : 60, product_details : 'FOAM WASH (Only Vehicle Wash)', product_quantity : 0, product_For: 'Vehicle Wash'},
  { product_id: 'pd351', product_img : '', product_name : 'Cars/Jeeps',
  product_price : 150, product_details : 'FOAM WASH (Only Vehicle Wash)', product_quantity : 0, product_For: 'Vehicle Wash'},

  // FOAM WASH & VACCUM for Vehicle Wash
  { product_id: 'pd352', product_img : '', product_name : 'Cars/Jeeps',
  product_price : 220, product_details : 'FOAM WASH & VACCUM (Only Vehicle Wash)', product_quantity : 0, product_For: 'Vehicle Wash'},

  // Shoe Polish for SHOE POLISH
  { product_id: 'pd353', product_img : '', product_name : 'Shoe',
  product_price : 25, product_details : 'SHOE POLISH (Only Shoe Polish)', product_quantity : 0, product_For: 'Shoe Polish'},
]

@Injectable({
  providedIn: 'root'
})
export class OrderService {
  order: Order;

  constructor(private http: HttpClient) {
    this.order = new Order;
    this.order.details = [];
  }

  public getProducts() {
    return products;
  }

  public getOrder() {
    return this.order;
  }

  public resetOrder(order: Order) {
    this.order = order;
    this.order.details = [];
    products.forEach(prod => {
      prod.product_quantity = 0;
    });
  }

  public AddOrderDetails(orderDetails: OrderDetails) {
    let apparelPresent: Boolean = false;
    this.order.details.forEach(orderDetail => {
      if (orderDetail.apparel === orderDetails.apparel) {
        orderDetail.quantity = orderDetails.quantity;
        apparelPresent = true
      }
    })

    if (!apparelPresent) {
      this.order.details.push(orderDetails);
    }
  }

  public AddFinalPrice(finalPrice: number) {
    this.order.finalPrice = finalPrice;
  }

  public AddCheckoutDetails(order: Order) {
    this.order.address = order.address;
    this.order.name = order.name;
    this.order.finalPrice = order.finalPrice;
    this.order.phone = order.phone;
    this.order.email = order.email;
    this.order.pickUpDateTime = order.pickUpDateTime;
    this.order.couponCode = order.couponCode;
    this.order.comments = order.comments;
  }

  public sendEmail(url, data) {
    return this.http.post(url, data);
  }
}
